JS Library: package.json
Composer Library: composer.json
Frontend: resources/**/*
Backend: app/**/*
Unit Test: tests/**/*
CircleCI Config: .circleci/**/*
Github Action: .github/**/*
Docker: docker-compose.yml
Documentation: README.md
