version: '2'

services:
    application:
        container_name: vue_fw7_application
        image: debian
        volumes:
            - ./:/var/www/laravel
    workspace:
        container_name: vue_fw7_workspace
        image: tranvanmy/laravel-workspace
        volumes_from:
            - application
        tty: true
    php-fpm:
        container_name: vue_fw7_php-fpm
        image: tranvanmy/laravel-php-fpm
        volumes_from:
            - application
        expose:
            - "2222"
        links:
            - workspace
    nginx:
        container_name: vue_fw7_nginx
        image: tranvanmy/laravel-nginx
        volumes_from:
            - data
            - logs
            - application
        ports:
            - "2025:80"
        links:
            - php-fpm
    data:
        container_name: vue_fw7_data
        image: debian
        volumes:
            - .docker/mysql:/var/lib/mysql
            - .docker/data:/data
    logs:
        container_name: Appvue_logs
        image: debian
        volumes:
            - .docker/logs/nginx:/var/log/nginx
            - .docker/logs/mongodb:/var/log/mongodb
    mysql:
        container_name: vue_fw7_mysql
        image: mysql:5.7
        volumes_from:
            - data
            - logs
        expose:
            - "3306"
        environment:
            MYSQL_DATABASE: vue
            MYSQL_USER: root
            MYSQL_PASSWORD: secret
            MYSQL_ROOT_PASSWORD: root
    mysql_test:
        container_name: vue_fw7_mysql_test
        restart: always
        image: mysql:5.7
        expose:
            - "3306"
        environment:
            MYSQL_DATABASE: vue_test
            MYSQL_USER: root
            MYSQL_PASSWORD: secret
            MYSQL_ROOT_PASSWORD: root
    phpmyadmin:
        container_name: vue_fw7_phpmyadmin
        image: phpmyadmin/phpmyadmin
        environment:
            PMA_ARBITRARY: 1
            MYSQL_USER: root
            MYSQL_PASSWORD: secret
            MYSQL_ROOT_PASSWORD: root
        ports:
            - "8085:80"
        links:
            - "mysql:mysql"

